from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AssetInput(BaseModel):
    title: str = Field(..., description="Name or title of the asset")
    asset_type: str = Field("image", description="Asset category: image, video, audio, bgm, chart, code, font")
    source: str = Field(..., description="Source where the asset was acquired")
    creator_provider: Optional[str] = Field(None, description="Author, artist, or provider")
    license_type: str = Field("Unknown", description="Declared license name or code")
    commercial_use_status: Optional[str] = Field(None, description="ALLOWED, PROHIBITED, RESTRICTED, or UNKNOWN")
    attribution_required: Optional[bool] = Field(None, description="Whether author attribution is legally required")
    attribution_text: Optional[str] = Field(None, description="Exact credit line to include in video or description")
    license_proof: Optional[str] = Field(None, description="URL or reference proving rights/license")
    expiry_date: Optional[str] = Field(None, description="License expiration date if time-bounded")
    is_ai_generated: bool = Field(False, description="Whether this asset was generated by an AI model")
    ai_tool: Optional[str] = Field(None, description="Name of the AI generator tool if applicable")
    content_item_id: Optional[str] = Field(None, description="Associated content item if linked")
    uri: Optional[str] = Field(None, description="Local or remote URI")
    notes: Optional[str] = Field(None, description="Editorial or legal notes")


class AssetRightsVerdict(BaseModel):
    asset_id: Optional[str] = None
    title: str
    status: str  # VERIFIED, UNKNOWN, REQUIRES_ATTRIBUTION, DO_NOT_USE
    is_safe: bool
    commercial_use_allowed: bool
    attribution_required: bool
    attribution_text: Optional[str] = None
    warnings: List[str] = Field(default_factory=list)
    explanation: str


class AssetRightsBatchVerdict(BaseModel):
    total_assets: int
    safe_count: int
    warning_count: int
    blocked_count: int
    all_safe: bool
    verdicts: List[AssetRightsVerdict] = Field(default_factory=list)
    summary: str
