import pytest
from httpx import AsyncClient


@pytest.mark.asyncio
async def test_asset_rights_seed_and_list(client: AsyncClient):
    # Seed starter assets
    seed_res = await client.post("/api/v1/asset-rights/seed-defaults")
    assert seed_res.status_code == 200
    starter_items = seed_res.json()
    assert len(starter_items) >= 4

    # List assets
    list_res = await client.get("/api/v1/asset-rights")
    assert list_res.status_code == 200
    items = list_res.json()
    assert len(items) >= 4

    # Filter by status
    verified_res = await client.get("/api/v1/asset-rights?status=VERIFIED")
    assert verified_res.status_code == 200
    verified_items = verified_res.json()
    assert all(item["status"] == "VERIFIED" for item in verified_items)


@pytest.mark.asyncio
async def test_asset_rights_summary_stats(client: AsyncClient):
    # Ensure seed is populated
    await client.post("/api/v1/asset-rights/seed-defaults")

    summary_res = await client.get("/api/v1/asset-rights/summary/stats")
    assert summary_res.status_code == 200
    stats = summary_res.json()
    assert "total_assets" in stats
    assert "verified" in stats
    assert "requires_attribution" in stats
    assert "unknown" in stats
    assert "do_not_use" in stats
    assert "safe_percentage" in stats
    assert stats["total_assets"] >= 4


@pytest.mark.asyncio
async def test_asset_rights_crud_lifecycle(client: AsyncClient):
    # Create new asset
    payload = {
        "title": "Custom Benchmark Chart 2026",
        "asset_type": "chart",
        "source": "Local ML Evaluation Script",
        "creator_provider": "Internal AI Lab",
        "license_type": "Self-Created",
        "license_proof": "Generated by eval.py commit #999",
        "notes": "Custom chart for episode 4",
    }
    create_res = await client.post("/api/v1/asset-rights", json=payload)
    assert create_res.status_code == 201
    created = create_res.json()
    assert created["id"] is not None
    assert created["status"] == "VERIFIED"
    assert created["attribution_required"] is False
    record_id = created["id"]

    # Get by ID
    get_res = await client.get(f"/api/v1/asset-rights/{record_id}")
    assert get_res.status_code == 200
    assert get_res.json()["title"] == "Custom Benchmark Chart 2026"

    # Update asset
    update_payload = {
        "notes": "Updated benchmark chart notes with revised latency metrics",
        "attribution_text": "Internal Lab Benchmark",
    }
    update_res = await client.put(f"/api/v1/asset-rights/{record_id}", json=update_payload)
    assert update_res.status_code == 200
    updated = update_res.json()
    assert updated["notes"] == "Updated benchmark chart notes with revised latency metrics"

    # Delete asset
    del_res = await client.delete(f"/api/v1/asset-rights/{record_id}")
    assert del_res.status_code == 204

    # Verify not found
    get_after_del = await client.get(f"/api/v1/asset-rights/{record_id}")
    assert get_after_del.status_code == 404


@pytest.mark.asyncio
async def test_asset_rights_live_evaluation(client: AsyncClient):
    # Live dry run check
    payload = {
        "title": "Royalty Free Sound Effect",
        "asset_type": "sfx",
        "source": "Freesound.org",
        "license_type": "CC0",
    }
    eval_res = await client.post("/api/v1/asset-rights/evaluate", json=payload)
    assert eval_res.status_code == 200
    verdict = eval_res.json()
    assert verdict["status"] == "VERIFIED"
    assert verdict["is_safe"] is True

    # Live batch check
    batch_payload = [
        {"title": "Safe Font", "asset_type": "font", "source": "Internal", "license_type": "MIT"},
        {"title": "Risky Photo", "asset_type": "image", "source": "Web", "license_type": "CC-BY-NC"},
    ]
    batch_res = await client.post("/api/v1/asset-rights/evaluate-batch", json=batch_payload)
    assert batch_res.status_code == 200
    batch_verdict = batch_res.json()
    assert batch_verdict["total_assets"] == 2
    assert batch_verdict["safe_count"] == 1
    assert batch_verdict["blocked_count"] == 1
    assert batch_verdict["all_safe"] is False
