"""create research packets and revisions tables

Revision ID: 9b75656e2a54
Revises: 86863a7d848d
Create Date: 2026-09-27 07:09:00.944116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b75656e2a54'
down_revision: Union[str, None] = '86863a7d848d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_packets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('primary_sources', sa.JSON(), nullable=False),
    sa.Column('supporting_sources', sa.JSON(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('numbers', sa.JSON(), nullable=False),
    sa.Column('dates', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('claims', sa.JSON(), nullable=False),
    sa.Column('contradictions', sa.JSON(), nullable=False),
    sa.Column('uncertain_claims', sa.JSON(), nullable=False),
    sa.Column('things_not_to_claim', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_packets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_packets_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_packets_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_packets_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_packets_topic'), ['topic'], unique=False)

    op.create_table('research_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('packet_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('change_summary', sa.String(length=512), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['research_packets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_revisions_packet_id'), ['packet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_revisions_packet_id'))

    op.drop_table('research_revisions')
    with op.batch_alter_table('research_packets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_packets_topic'))
        batch_op.drop_index(batch_op.f('ix_research_packets_slug'))
        batch_op.drop_index(batch_op.f('ix_research_packets_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_research_packets_is_verified'))

    op.drop_table('research_packets')
    # ### end Alembic commands ###
