"""create evidence and provenance tables

Revision ID: 7452bf889f0f
Revises: 9b75656e2a54
Create Date: 2026-09-27 12:03:45.791322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7452bf889f0f'
down_revision: Union[str, None] = '9b75656e2a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('tools_models', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_title'), ['title'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('packet_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['research_packets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_claim_type'), ['claim_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_packet_id'), ['packet_id'], unique=False)

    op.create_table('evidence_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('packet_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('trust_weight', sa.Float(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['research_packets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_sources_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_sources_packet_id'), ['packet_id'], unique=False)

    op.create_table('experiment_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_runs_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('claim_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('page_or_timestamp', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_evidence_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidence_source_id'), ['source_id'], unique=False)

    op.create_table('conclusions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conclusions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conclusions_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conclusions_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('content_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=100), nullable=False),
    sa.Column('quote_in_script', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_claims_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_claims_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_claims_verification_status'), ['verification_status'], unique=False)

    op.create_table('measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_run_id'))
        batch_op.drop_index(batch_op.f('ix_measurements_metric'))

    op.drop_table('measurements')
    with op.batch_alter_table('content_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_claims_verification_status'))
        batch_op.drop_index(batch_op.f('ix_content_claims_content_id'))
        batch_op.drop_index(batch_op.f('ix_content_claims_claim_id'))

    op.drop_table('content_claims')
    with op.batch_alter_table('conclusions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conclusions_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_conclusions_claim_id'))

    op.drop_table('conclusions')
    with op.batch_alter_table('claim_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_evidence_source_id'))
        batch_op.drop_index(batch_op.f('ix_claim_evidence_claim_id'))

    op.drop_table('claim_evidence')
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_runs_experiment_id'))

    op.drop_table('experiment_runs')
    with op.batch_alter_table('evidence_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_sources_packet_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_sources_domain'))

    op.drop_table('evidence_sources')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_packet_id'))
        batch_op.drop_index(batch_op.f('ix_claims_is_verified'))
        batch_op.drop_index(batch_op.f('ix_claims_claim_type'))

    op.drop_table('claims')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_title'))
        batch_op.drop_index(batch_op.f('ix_experiments_opportunity_id'))

    op.drop_table('experiments')
    # ### end Alembic commands ###
