"""retrofit_brand_memory_and_monetization

Revision ID: 015e647e5750
Revises: c4635f03662e
Create Date: 2026-09-27 06:17:57.690200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015e647e5750'
down_revision: Union[str, None] = 'c4635f03662e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_note', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_memory_memory_type'), ['memory_type'], unique=False)

    with op.batch_alter_table('brand_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_lead_magnet', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('newsletter_cta', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('digital_product_cta', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_profiles', schema=None) as batch_op:
        batch_op.drop_column('digital_product_cta')
        batch_op.drop_column('newsletter_cta')
        batch_op.drop_column('default_lead_magnet')

    with op.batch_alter_table('brand_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_memory_memory_type'))

    op.drop_table('brand_memory')
    # ### end Alembic commands ###
