"""create_initial_schema

Revision ID: bef45dd518f6
Revises: 
Create Date: 2026-09-27 05:44:59.694985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef45dd518f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('brand_exemplars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_note', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('brand_promise', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('tone', sa.JSON(), nullable=False),
    sa.Column('voice_rules', sa.JSON(), nullable=False),
    sa.Column('preferred_vocabulary', sa.JSON(), nullable=False),
    sa.Column('avoid_vocabulary', sa.JSON(), nullable=False),
    sa.Column('banned_cliches', sa.JSON(), nullable=False),
    sa.Column('claim_rules', sa.JSON(), nullable=False),
    sa.Column('cta_style', sa.Text(), nullable=False),
    sa.Column('humor_policy', sa.Text(), nullable=False),
    sa.Column('controversy_policy', sa.Text(), nullable=False),
    sa.Column('sponsor_policy', sa.Text(), nullable=False),
    sa.Column('affiliate_disclosure_style', sa.Text(), nullable=False),
    sa.Column('visual_identity', sa.JSON(), nullable=False),
    sa.Column('platform_adaptations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niche_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('one_sentence_definition', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('audience_regions', sa.JSON(), nullable=False),
    sa.Column('primary_problems', sa.JSON(), nullable=False),
    sa.Column('allowed_topics', sa.JSON(), nullable=False),
    sa.Column('adjacent_topics', sa.JSON(), nullable=False),
    sa.Column('blocked_topics', sa.JSON(), nullable=False),
    sa.Column('must_have_signals', sa.JSON(), nullable=False),
    sa.Column('negative_keywords', sa.JSON(), nullable=False),
    sa.Column('preferred_source_types', sa.JSON(), nullable=False),
    sa.Column('content_pillars', sa.JSON(), nullable=False),
    sa.Column('commercial_intent_topics', sa.JSON(), nullable=False),
    sa.Column('evergreen_topics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_settings',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('channel_url', sa.String(length=1024), nullable=False),
    sa.Column('publishing_url', sa.String(length=1024), nullable=False),
    sa.Column('account_handle', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_settings')
    op.drop_table('niche_profiles')
    op.drop_table('brand_profiles')
    op.drop_table('brand_exemplars')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
