"""create opportunities table

Revision ID: 86863a7d848d
Revises: 993c3b7083c5
Create Date: 2026-09-27 07:00:15.301040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86863a7d848d'
down_revision: Union[str, None] = '993c3b7083c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('trend_id', sa.String(length=36), nullable=True),
    sa.Column('pillar', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('niche_fit_score', sa.Float(), nullable=False),
    sa.Column('originality_potential', sa.Float(), nullable=False),
    sa.Column('audience_usefulness', sa.Float(), nullable=False),
    sa.Column('evergreen_value', sa.Float(), nullable=False),
    sa.Column('commercial_fit', sa.Float(), nullable=False),
    sa.Column('content_family_potential', sa.Float(), nullable=False),
    sa.Column('sponsor_relevance', sa.Float(), nullable=False),
    sa.Column('saturation_penalty', sa.Float(), nullable=False),
    sa.Column('production_effort', sa.String(length=50), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=False),
    sa.Column('suggested_original_angle', sa.Text(), nullable=False),
    sa.Column('suggested_content_family', sa.String(length=100), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.String(length=50), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('source_references', sa.JSON(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['discovered_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trend_id'], ['trend_topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_opportunity_score'), ['opportunity_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_pillar'), ['pillar'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_opportunities_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_status'))
        batch_op.drop_index(batch_op.f('ix_opportunities_slug'))
        batch_op.drop_index(batch_op.f('ix_opportunities_pillar'))
        batch_op.drop_index(batch_op.f('ix_opportunities_opportunity_score'))

    op.drop_table('opportunities')
    # ### end Alembic commands ###
