"""create_engine_runs_table

Revision ID: c4635f03662e
Revises: bef45dd518f6
Create Date: 2026-09-27 05:51:02.410729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4635f03662e'
down_revision: Union[str, None] = 'bef45dd518f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('input_count', sa.Integer(), nullable=False),
    sa.Column('output_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('explanations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_runs_engine_id'), ['engine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_runs_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engine_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_engine_runs_engine_id'))

    op.drop_table('engine_runs')
    # ### end Alembic commands ###
