"""create trend topics and trend history tables

Revision ID: 993c3b7083c5
Revises: fe9a759aed8a
Create Date: 2026-09-27 06:52:31.252533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993c3b7083c5'
down_revision: Union[str, None] = 'fe9a759aed8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('pillar', sa.String(length=128), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('distinct_sources_count', sa.Integer(), nullable=False),
    sa.Column('source_diversity_score', sa.Float(), nullable=False),
    sa.Column('source_authority_score', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('velocity_ratio', sa.Float(), nullable=False),
    sa.Column('historical_baseline', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manual_boost', sa.Float(), nullable=False),
    sa.Column('is_suppressed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('signal_ids', sa.JSON(), nullable=False),
    sa.Column('source_breakdown', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trend_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_topics_is_suppressed'), ['is_suppressed'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_topics_pillar'), ['pillar'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_topics_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_topics_topic_key'), ['topic_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_trend_topics_trend_score'), ['trend_score'], unique=False)

    op.create_table('trend_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['trend_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trend_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_history_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_history_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trend_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_history_topic_id'))
        batch_op.drop_index(batch_op.f('ix_trend_history_recorded_at'))

    op.drop_table('trend_history')
    with op.batch_alter_table('trend_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_topics_trend_score'))
        batch_op.drop_index(batch_op.f('ix_trend_topics_topic_key'))
        batch_op.drop_index(batch_op.f('ix_trend_topics_status'))
        batch_op.drop_index(batch_op.f('ix_trend_topics_pillar'))
        batch_op.drop_index(batch_op.f('ix_trend_topics_is_suppressed'))

    op.drop_table('trend_topics')
    # ### end Alembic commands ###
