"""create rss feeds and discovered candidates tables

Revision ID: fe9a759aed8a
Revises: 7b8e1a34d2c9
Create Date: 2026-09-27 06:40:25.087225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9a759aed8a'
down_revision: Union[str, None] = '7b8e1a34d2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('normalized_title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('primary_source', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('pillar', sa.String(length=128), nullable=True),
    sa.Column('niche_score', sa.Float(), nullable=False),
    sa.Column('is_in_niche', sa.Boolean(), nullable=False),
    sa.Column('niche_verdict', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovered_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_candidates_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_candidates_content_fingerprint'), ['content_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_candidates_is_in_niche'), ['is_in_niche'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_candidates_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_candidates_status'), ['status'], unique=False)

    op.create_table('rss_feeds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('trust_weight', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rss_feeds')
    with op.batch_alter_table('discovered_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_discovered_candidates_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_discovered_candidates_is_in_niche'))
        batch_op.drop_index(batch_op.f('ix_discovered_candidates_content_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_discovered_candidates_canonical_url'))

    op.drop_table('discovered_candidates')
    # ### end Alembic commands ###
