"""create_ai_invocation_logs_table

Revision ID: a0870b082f7d
Revises: 7452bf889f0f
Create Date: 2026-09-27 12:25:35.127749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0870b082f7d'
down_revision: Union[str, None] = '7452bf889f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_invocation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.Text(), nullable=True),
    sa.Column('primary_provider', sa.String(length=50), nullable=True),
    sa.Column('primary_error', sa.Text(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_invocation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_invocation_logs_fallback_used'), ['fallback_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_invocation_logs_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_invocation_logs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_invocation_logs_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_invocation_logs_task'), ['task'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_invocation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_invocation_logs_task'))
        batch_op.drop_index(batch_op.f('ix_ai_invocation_logs_success'))
        batch_op.drop_index(batch_op.f('ix_ai_invocation_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_invocation_logs_model'))
        batch_op.drop_index(batch_op.f('ix_ai_invocation_logs_fallback_used'))

    op.drop_table('ai_invocation_logs')
    # ### end Alembic commands ###
